### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by khushaljethava** [pwill0217/RoomRevive#1]
Can you share steps and sample of the dataset?

**Comment by pwill0217** [comment]
I can provide you with the steps, but as far as a sample of the dataset goes I don't have a sample of it but check out this github: https://github.com/thijssdaniels . That is the person who made the repo and trained the model. you can find the model on replicate here: https://replicate.com/thijssdaniels/room-gpt.


Steps I took:
I installed replicate and streamline.
used the replicate api
